# -*- coding: utf-8 -*-
"""vision.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dI7NWRPSJFTAhG1kak3iOKMjN49sNMAG
"""

from google.colab import drive
drive.mount('/content/drive')

!git clone https://github.com/ultralytics/yolov5

!pip install -r yolov5/requirements.txt

#!cd yolov5/
!python yolov5/train.py --img 1024 --batch 10 --epochs 10 --data lidar_data.yaml --weights yolov5m.pt

!python yolov5/train.py --resume

!python yolov5/train.py --img 1024 --batch 10 --epochs 10 --data lidar_data.yaml --weights best.pt --cache --evolve

!tensorboard --logdir yolov5/runs/train

!pip install wandb

!environ['PYTHONWARNINGS'] = 'ignore:semaphore_tracker:UserWarning'

!python yolov5/val.py --data lidar_data.yaml --weights best.pt

!pip install -r https://raw.githubusercontent.com/ultralytics/yolov5/master/requirements.txt

import cv2
import torch
from PIL import Image

def copy_attr(a, b, include=(), exclude=()):
    # Copy attributes from b to a, options to only include [...] and to exclude [...]
    for k, v in b.__dict__.items():
        if (len(include) and k not in include) or k.startswith('_') or k in exclude:
            continue
        else:
            setattr(a, k, v)

import torch
import os
path = "drive/MyDrive/test/images/"
model = torch.hub.load('ultralytics/yolov5', 'custom', path='model/best.pt', force_reload=True)
#model.load_state_dict(torch.load('model/best.pt')['model'].state_dict())

#model = model.fuse().autoshape()

for img in os.listdir(path):
  results = model(path + img, size=1024)
  results.save("aresults")
